import { ProjectStatusBadge } from "@/components/ProjectStatusBadge";
import { Button } from "@/components/ui/button";
import { formatDate, formatDuration, stageLabel } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Plus, Video } from "lucide-react";
import { useLocation } from "wouter";

export default function ProjectsPage() {
  const [, navigate] = useLocation();
  const list = trpc.projects.list.useQuery();
  return <div className="mx-auto max-w-7xl space-y-6 pb-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">Production library</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Project history</h1><p className="mt-2 text-sm text-muted-foreground">Every upload, stage outcome, and final Tamil output in one secure workspace.</p></div><Button onClick={() => navigate("/upload")} className="gap-2 rounded-xl"><Plus className="h-4 w-4" />New project</Button></div><section className="overflow-hidden rounded-3xl border border-border/70 bg-card shadow-sm">{list.isLoading ? <div className="p-8 text-sm text-muted-foreground">Loading projects…</div> : list.data?.length ? <div className="divide-y divide-border/60">{list.data.map(project => <button key={project.id} onClick={() => navigate(`/projects/${project.id}`)} className="flex w-full flex-col gap-4 px-5 py-5 text-left transition-colors hover:bg-muted/35 sm:flex-row sm:items-center sm:px-6"><div className="flex h-16 w-full items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-violet-500/25 via-fuchsia-500/15 to-cyan-500/20 sm:w-24">{project.thumbnailUrl ? <img src={project.thumbnailUrl} alt="" className="h-full w-full object-cover" /> : <Video className="h-6 w-6 text-violet-500" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{project.projectName}</p><ProjectStatusBadge status={project.status} /></div><p className="mt-1.5 text-sm text-muted-foreground">{project.detectedLanguage || project.originalLanguage} → Tamil · {formatDuration(project.sourceDurationSeconds)} · {stageLabel(project.currentStage)}</p><p className="mt-1 text-xs text-muted-foreground">Created {formatDate(project.createdAt)}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></button>)}</div> : <div className="flex flex-col items-center px-6 py-16 text-center"><Video className="h-8 w-8 text-violet-500" /><h2 className="mt-4 font-semibold">No projects yet</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">Upload an authorized MP4, MOV, MKV, or WebM file to begin a Tamil dubbing workflow.</p></div>}</section></div>;
}
