import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { formatBytes, formatDuration } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowLeft, Check, CloudUpload, FileVideo2, Loader2, ShieldCheck, Sparkles, Subtitles, Volume2 } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const voices = [
  { id: "female-1", name: "Tamil expressive", detail: "Natural and conversational" },
  { id: "female-2", name: "Tamil crisp", detail: "Bright explainer delivery" },
  { id: "male-1", name: "Tamil balanced", detail: "Even and clear delivery" },
  { id: "male-2", name: "Tamil warm", detail: "Grounded, lower-register tone" },
  { id: "narrator", name: "Tamil narrator", detail: "Measured documentary read" },
  { id: "youth", name: "Tamil youthful", detail: "Energetic social-first delivery" },
] as const;
const styles = ["natural", "professional", "friendly", "documentary", "energetic"] as const;
const subtitleStyles = [{ id: "studio", name: "Studio" }, { id: "minimal", name: "Minimal" }, { id: "high_contrast", name: "High contrast" }] as const;
type VoiceId = (typeof voices)[number]["id"];
type VoiceStyle = (typeof styles)[number];
type SubtitleStyle = (typeof subtitleStyles)[number]["id"];

function mime(file: File) { const ext = file.name.split(".").pop()?.toLowerCase(); return file.type || ({ mp4: "video/mp4", mov: "video/quicktime", mkv: "video/x-matroska", webm: "video/webm" } as Record<string, string>)[ext || ""] || ""; }
function upload(file: File, path: string, setProgress: (value: number) => void) { return new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open("POST", path); xhr.setRequestHeader("Content-Type", mime(file)); xhr.upload.onprogress = event => { if (event.lengthComputable) setProgress(Math.round(event.loaded / event.total * 100)); }; xhr.onerror = () => reject(new Error("The video could not reach secure project storage. Check your connection and try again.")); xhr.onload = () => { if (xhr.status >= 200 && xhr.status < 300) return resolve(); try { reject(new Error((JSON.parse(xhr.responseText) as { error?: string }).error || "Upload failed.")); } catch { reject(new Error(`Upload failed with status ${xhr.status}.`)); } }; xhr.send(file); }); }

export default function UploadPage() {
  const [, navigate] = useLocation();
  const fileInput = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null); const [duration, setDuration] = useState<number | null>(null); const [dragging, setDragging] = useState(false); const [progress, setProgress] = useState(0);
  const [projectName, setProjectName] = useState(""); const [originalLanguage, setOriginalLanguage] = useState("auto"); const [voiceId, setVoiceId] = useState<VoiceId>("female-1"); const [voiceStyle, setVoiceStyle] = useState<VoiceStyle>("natural");
  const [terminologyRules, setTerminologyRules] = useState(""); const [pronunciationRules, setPronunciationRules] = useState(""); const [subtitleStyle, setSubtitleStyle] = useState<SubtitleStyle>("studio"); const [allowVoiceProviderFallback, setAllowVoiceProviderFallback] = useState(true);
  const [preserveBackgroundAudio, setPreserveBackgroundAudio] = useState(true); const [preserveSoundEffects, setPreserveSoundEffects] = useState(true); const [generateSubtitles, setGenerateSubtitles] = useState(true); const [burnSubtitles, setBurnSubtitles] = useState(false); const [createSrt, setCreateSrt] = useState(true);
  const [ownershipConfirmed, setOwnershipConfirmed] = useState(false); const [responsibilityConfirmed, setResponsibilityConfirmed] = useState(false);
  const prepare = trpc.projects.prepareUpload.useMutation(); const complete = trpc.projects.completeUpload.useMutation(); const start = trpc.projects.startProcessing.useMutation();
  const busy = prepare.isPending || complete.isPending || start.isPending || (progress > 0 && progress < 100);

  function select(selected?: File) {
    if (!selected) return;
    if (!/[.](mp4|mov|mkv|webm)$/i.test(selected.name)) return toast.error("Use an MP4, MOV, MKV, or WebM video file.");
    if (selected.size > 200 * 1024 * 1024) return toast.error("This MVP currently supports videos up to 200 MB.");
    setFile(selected); setProjectName(value => value || selected.name.replace(/\.[^.]+$/, "")); setProgress(0);
    const video = document.createElement("video"); video.preload = "metadata"; video.onloadedmetadata = () => { setDuration(video.duration); URL.revokeObjectURL(video.src); }; video.src = URL.createObjectURL(selected);
  }
  async function submit() {
    if (!file) return toast.error("Choose a video to continue.");
    if (!ownershipConfirmed || !responsibilityConfirmed) return toast.error("Confirm both copyright acknowledgements before processing.");
    try {
      const mimeType = mime(file);
      const prepared = await prepare.mutateAsync({ projectName, originalLanguage, voiceId, voiceStyle, terminologyRules, pronunciationRules, subtitleStyle, allowVoiceProviderFallback, preserveBackgroundAudio, preserveSoundEffects, generateSubtitles, burnSubtitles, createSrt, copyrightOwnershipConfirmed: true, copyrightResponsibilityConfirmed: true, filename: file.name, mimeType, sizeBytes: file.size });
      await upload(file, prepared.uploadPath, setProgress); await complete.mutateAsync({ projectId: prepared.projectId, file: { filename: file.name, mimeType, sizeBytes: file.size } }); await start.mutateAsync({ projectId: prepared.projectId }); toast.success("Upload complete. Tamil dubbing has started."); navigate(`/projects/${prepared.projectId}`);
    } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to start the dubbing project."); setProgress(0); }
  }

  return <div className="mx-auto max-w-6xl space-y-7 pb-12"><header className="flex items-center gap-3"><Button variant="ghost" size="icon" className="rounded-xl" onClick={() => navigate("/")}><ArrowLeft className="h-4 w-4" /></Button><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-violet-600 dark:text-violet-300">New production</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Create a Tamil dub</h1></div></header><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><main className="space-y-6">
    <section className="rounded-3xl border border-border/70 bg-card p-5 shadow-sm sm:p-7"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">1. Upload your video</h2><p className="mt-1 text-sm text-muted-foreground">Direct upload only. MP4, MOV, MKV, and WebM up to 200 MB.</p></div><FileVideo2 className="h-5 w-5 text-violet-500" /></div><button type="button" onClick={() => fileInput.current?.click()} onDragOver={event => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); select(event.dataTransfer.files[0]); }} className={`mt-5 flex min-h-52 w-full flex-col items-center justify-center rounded-2xl border border-dashed px-6 text-center ${dragging ? "border-violet-500 bg-violet-500/10" : "border-border bg-muted/25 hover:border-violet-400"}`}><div className="rounded-2xl bg-violet-500/10 p-3 text-violet-500"><CloudUpload className="h-6 w-6" /></div>{file ? <><p className="mt-4 max-w-full truncate font-semibold">{file.name}</p><p className="mt-1 text-sm text-muted-foreground">{formatBytes(file.size)} · {formatDuration(duration)}</p><span className="mt-3 text-sm font-medium text-violet-600 dark:text-violet-300">Choose another file</span></> : <><p className="mt-4 font-semibold">Drop your video here</p><p className="mt-1 text-sm text-muted-foreground">or browse from your computer</p></>}</button><input ref={fileInput} type="file" accept=".mp4,.mov,.mkv,.webm,video/*" className="hidden" onChange={event => select(event.target.files?.[0])} />{progress > 0 ? <div className="mt-5"><div className="mb-2 flex justify-between text-xs text-muted-foreground"><span>Uploading securely to project storage</span><span>{progress}%</span></div><Progress value={progress} /></div> : null}</section>
    <section className="rounded-3xl border border-border/70 bg-card p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/10 p-2.5 text-cyan-500"><Volume2 className="h-5 w-5" /></div><div><h2 className="font-semibold">2. Localize for Tamil</h2><p className="text-sm text-muted-foreground">Control translation choices, Tamil voice, and spoken pronunciation.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Project name"><Input value={projectName} onChange={event => setProjectName(event.target.value)} /></Field><Field label="Original language"><select value={originalLanguage} onChange={event => setOriginalLanguage(event.target.value)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{[["auto", "Auto detect"], ["en", "English"], ["hi", "Hindi"], ["te", "Telugu"], ["ml", "Malayalam"], ["kn", "Kannada"]].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></Field></div><div className="mt-5"><Label>Tamil voice profile</Label><div className="mt-2 grid gap-2 sm:grid-cols-2">{voices.map(voice => <button key={voice.id} type="button" onClick={() => setVoiceId(voice.id)} className={`rounded-xl border p-3 text-left ${voiceId === voice.id ? "border-violet-500 bg-violet-500/10" : "border-border hover:bg-muted/50"}`}><div className="flex justify-between"><span className="text-sm font-semibold">{voice.name}</span>{voiceId === voice.id ? <Check className="h-4 w-4 text-violet-500" /> : null}</div><p className="mt-1 text-xs text-muted-foreground">{voice.detail}</p></button>)}</div></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Voice style"><select value={voiceStyle} onChange={event => setVoiceStyle(event.target.value as VoiceStyle)} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{styles.map(style => <option key={style}>{style}</option>)}</select></Field><Toggle title="Use configured backup voice provider" detail="Used only when a compatible administrator-configured fallback is available." value={allowVoiceProviderFallback} onChange={setAllowVoiceProviderFallback} /></div><Rules label="Terminology rules" hint="Use `source => Tamil preferred term` on each line. Rules guide translation." value={terminologyRules} onChange={setTerminologyRules} placeholder="AI => செயற்கை நுண்ணறிவு\nDashboard => டாஷ்போர்டு" /><Rules label="Pronunciation rules" hint="Use `spoken form => preferred spoken form` for Tamil voice generation." value={pronunciationRules} onChange={setPronunciationRules} placeholder="OpenAI => ஓபன் ஏஐ\nSaaS => சாஸ்" /></section>
    <section className="rounded-3xl border border-border/70 bg-card p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-500"><Subtitles className="h-5 w-5" /></div><div><h2 className="font-semibold">3. Subtitle and audio finish</h2><p className="text-sm text-muted-foreground">Set the caption treatment and source-audio preferences.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{subtitleStyles.map(style => <button key={style.id} type="button" onClick={() => setSubtitleStyle(style.id)} className={`rounded-xl border p-3 text-left ${subtitleStyle === style.id ? "border-violet-500 bg-violet-500/10" : "border-border"}`}><p className="text-sm font-semibold">{style.name}</p><p className="mt-1 text-xs text-muted-foreground">{style.id === "studio" ? "Bold Tamil captions" : style.id === "minimal" ? "Subtle captions" : "High-legibility captions"}</p></button>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Toggle title="Preserve background music" detail="Uses safe replacement-audio fallback where separation is unavailable." value={preserveBackgroundAudio} onChange={setPreserveBackgroundAudio} /><Toggle title="Preserve sound effects" detail="Available when an audio-separation provider is configured." value={preserveSoundEffects} onChange={setPreserveSoundEffects} /><Toggle title="Generate Tamil subtitles" detail="Creates timed captions from approved translations." value={generateSubtitles} onChange={setGenerateSubtitles} /><Toggle title="Burn captions into MP4" detail="Renders your selected Tamil caption style into video." value={burnSubtitles} onChange={setBurnSubtitles} /><Toggle title="Create separate SRT file" detail="Provides a downloadable Tamil subtitle file." value={createSrt} onChange={setCreateSrt} /></div></section>
  </main><aside className="h-fit space-y-5 lg:sticky lg:top-6"><section className="rounded-3xl border border-amber-400/25 bg-amber-400/5 p-5 shadow-sm"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-600 dark:text-amber-300" /><div><h2 className="font-semibold">Copyright and permission</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">You must own this video or have permission or a valid license to translate, dub, modify, and republish it.</p></div></div><div className="mt-5 space-y-4"><label className="flex gap-3 text-sm"><Checkbox checked={ownershipConfirmed} onCheckedChange={value => setOwnershipConfirmed(value === true)} /><span>I own this content or have permission to modify and dub it.</span></label><label className="flex gap-3 text-sm"><Checkbox checked={responsibilityConfirmed} onCheckedChange={value => setResponsibilityConfirmed(value === true)} /><span>I understand that I am responsible for copyright compliance.</span></label></div></section><section className="rounded-3xl border border-border/70 bg-card p-5 shadow-sm"><h2 className="font-semibold">Processing sequence</h2><ol className="mt-4 space-y-2.5 text-sm text-muted-foreground">{["Extract audio", "Detect language", "Transcribe with timestamps", "Translate using localization rules", "Generate Tamil voice", "Synchronize and render MP4"].map((step, index) => <li key={step} className="flex gap-3"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-500/10 text-xs font-semibold text-violet-600 dark:text-violet-300">{index + 1}</span>{step}</li>)}</ol><Button onClick={submit} disabled={busy || !file || !ownershipConfirmed || !responsibilityConfirmed || !projectName.trim()} className="mt-6 w-full gap-2 rounded-xl bg-violet-600 hover:bg-violet-500">{busy ? <><Loader2 className="h-4 w-4 animate-spin" />{progress ? `Uploading ${progress}%` : "Preparing project"}</> : <><Sparkles className="h-4 w-4" />Start Tamil dubbing</>}</Button></section><div className="flex gap-2 rounded-2xl border border-border/70 bg-muted/35 p-3 text-xs leading-5 text-muted-foreground"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-500" />Long production renders require the documented durable FFmpeg worker configuration.</div></aside></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Rules({ label, hint, value, onChange, placeholder }: { label: string; hint: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="mt-5 space-y-2"><div className="flex justify-between gap-4"><Label>{label}</Label><span className="text-xs text-muted-foreground">One rule per line</span></div><Textarea value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="min-h-24 font-mono text-xs leading-5" /><p className="text-xs text-muted-foreground">{hint}</p></div>; }
function Toggle({ title, detail, value, onChange }: { title: string; detail: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-start justify-between gap-3 rounded-xl border border-border/70 p-3.5"><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div><Switch checked={value} onCheckedChange={onChange} /></div>; }
